import * as about from "./about"
import * as contact from "./contact"
import * as experience from "./experience"
import * as flows from "./flows"
import * as heroes from "./heroes"
import * as projects from "./projects"
import * as skills from "./skills"
import type { Candidate } from "./types"

/** The 40 candidate sections for the 2D portfolio, numbered for picking. */
export const CANDIDATES: Candidate[] = [
  {
    id: "sunset-hero",
    name: "Sunset Hero",
    category: "hero",
    note: "Outrun sun, racing CSS grid, big neon name and two CTAs.",
    Component: heroes.SunsetHero,
  },
  {
    id: "terminal-hero",
    name: "Terminal Hero",
    category: "hero",
    note: "Intro copy beside a shell that types out whoami / stack / hire.",
    Component: heroes.TerminalHero,
  },
  {
    id: "glitch-hero",
    name: "Glitch Hero",
    category: "hero",
    note: "RGB-split glitching name on a scanlined slab.",
    Component: heroes.GlitchHero,
  },
  {
    id: "spotlight-hero",
    name: "Spotlight Hero",
    category: "hero",
    note: "Pointer-follow flashlight revealing a hidden grid.",
    Component: heroes.SpotlightHero,
  },
  {
    id: "marquee-hero",
    name: "Marquee Hero",
    category: "hero",
    note: "Oversized outlined skill bands sliding in opposite directions.",
    Component: heroes.MarqueeHero,
  },
  {
    id: "attract-hero",
    name: "Attract Mode",
    category: "hero",
    note: "Arcade attract screen: high score table and blinking INSERT COIN.",
    Component: heroes.AttractHero,
  },
  {
    id: "split-flap-hero",
    name: "Split-Flap Board",
    category: "hero",
    note: "Airport departure board cycling through your roles.",
    Component: heroes.SplitFlapHero,
  },
  {
    id: "holo-card-hero",
    name: "Holo Card",
    category: "hero",
    note: "Holographic trading card that tilts with the pointer.",
    Component: heroes.HoloCardHero,
  },
  {
    id: "stats-counter",
    name: "Stats Counter",
    category: "about",
    note: "Years, projects, skills and posts counting up on scroll.",
    Component: about.StatsCounter,
  },
  {
    id: "bento-about",
    name: "Bento About",
    category: "about",
    note: "Bento grid: bio, location, current role, skills, links.",
    Component: about.BentoAbout,
  },
  {
    id: "character-sheet",
    name: "Character Sheet",
    category: "about",
    note: "RPG stat sheet with segmented attribute bars.",
    Component: about.CharacterSheet,
  },
  {
    id: "now-board",
    name: "Now Board",
    category: "about",
    note: "Live-dot 'now' panel: building, writing, playing.",
    Component: about.NowBoard,
  },
  {
    id: "manifesto",
    name: "Manifesto",
    category: "about",
    note: "Tagline as a giant shimmering pull quote.",
    Component: about.Manifesto,
  },
  {
    id: "rpg-dialog",
    name: "RPG Dialog",
    category: "about",
    note: "Bio in a retro JRPG dialogue box.",
    Component: about.RpgDialog,
  },
  {
    id: "skills-graph",
    name: "Skills Graph",
    category: "skills",
    note: "React Flow: draggable skill graph radiating from you.",
    flow: true,
    Component: flows.SkillsGraph,
  },
  {
    id: "skill-radar",
    name: "Skill Radar",
    category: "skills",
    note: "Animated SVG radar chart with a legend.",
    Component: skills.SkillRadar,
  },
  {
    id: "skill-orbit",
    name: "Skill Orbit",
    category: "skills",
    note: "Skills orbiting your initial; inner ring = strongest.",
    Component: skills.SkillOrbit,
  },
  {
    id: "skill-equalizer",
    name: "Skill Equalizer",
    category: "skills",
    note: "Each skill is a dancing graphic-EQ band.",
    Component: skills.SkillEqualizer,
  },
  {
    id: "skill-cloud",
    name: "Skill Cloud",
    category: "skills",
    note: "Weighted tag cloud (skills + project stack), glows on hover.",
    Component: skills.SkillCloud,
  },
  {
    id: "skill-rings",
    name: "Skill Rings",
    category: "skills",
    note: "Progress rings with frontend / backend / tools tabs.",
    Component: skills.SkillRings,
  },
  {
    id: "tech-marquee",
    name: "Tech Marquee",
    category: "skills",
    note: "Two infinite rows of tech chips, edge-faded.",
    Component: skills.TechMarquee,
  },
  {
    id: "project-carousel",
    name: "Project Carousel",
    category: "projects",
    note: "Snap-scrolling cards with arrows and procedural thumbnails.",
    Component: projects.ProjectCarousel,
  },
  {
    id: "cabinet-cards",
    name: "Cabinet Cards",
    category: "projects",
    note: "Each project as a little arcade cabinet: marquee, screen, buttons.",
    Component: projects.CabinetCards,
  },
  {
    id: "flip-cards",
    name: "Flip Cards",
    category: "projects",
    note: "3D flip: summary front, stack and link back.",
    Component: projects.FlipCards,
  },
  {
    id: "architecture-flow",
    name: "Architecture Flow",
    category: "projects",
    note: "React Flow: per-project request pipeline built from its stack.",
    flow: true,
    Component: flows.ArchitectureFlow,
  },
  {
    id: "project-accordion",
    name: "Project Accordion",
    category: "projects",
    note: "Horizontal accordion; the hovered panel expands.",
    Component: projects.ProjectAccordion,
  },
  {
    id: "spotlight-list",
    name: "Spotlight List",
    category: "projects",
    note: "Big numbered list with an animated preview pane.",
    Component: projects.SpotlightList,
  },
  {
    id: "stacked-deck",
    name: "Stacked Deck",
    category: "projects",
    note: "A deck of cards that fans out on hover.",
    Component: projects.StackedDeck,
  },
  {
    id: "filter-grid",
    name: "Filter Grid",
    category: "projects",
    note: "Tag chips with a sliding pill and animated re-layout.",
    Component: projects.FilterGrid,
  },
  {
    id: "career-flow",
    name: "Career Flow",
    category: "experience",
    note: "React Flow: jobs on a track with the projects they produced.",
    flow: true,
    Component: flows.CareerFlow,
  },
  {
    id: "glow-timeline",
    name: "Glow Timeline",
    category: "experience",
    note: "Alternating timeline with glowing nodes, reveals on scroll.",
    Component: experience.GlowTimeline,
  },
  {
    id: "level-map",
    name: "Level Map",
    category: "experience",
    note: "Career as a platformer world map; click a level.",
    Component: experience.LevelMap,
  },
  {
    id: "activity-heatmap",
    name: "Activity Heatmap",
    category: "experience",
    note: "Contribution-style heatmap in neon pink (decorative).",
    Component: experience.ActivityHeatmap,
  },
  {
    id: "git-log",
    name: "Git Log",
    category: "experience",
    note: "Projects and jobs as `git log --graph`.",
    Component: experience.GitLog,
  },
  {
    id: "blog-magazine",
    name: "Blog Magazine",
    category: "blog",
    note: "Featured post tile plus a numbered list.",
    Component: contact.BlogMagazine,
  },
  {
    id: "blog-ls",
    name: "Blog ls -la",
    category: "blog",
    note: "Posts as a directory listing.",
    Component: contact.BlogLs,
  },
  {
    id: "magnetic-cta",
    name: "Magnetic CTA",
    category: "contact",
    note: "Huge call to action with a button that follows the pointer.",
    Component: contact.MagneticCta,
  },
  {
    id: "terminal-contact",
    name: "Terminal Contact",
    category: "contact",
    note: "Step-by-step prompt form that hands off to email.",
    Component: contact.TerminalContact,
  },
  {
    id: "social-dock",
    name: "Social Dock",
    category: "contact",
    note: "macOS-style magnifying dock for links and resume.",
    Component: contact.SocialDock,
  },
  {
    id: "skyline-footer",
    name: "Skyline Footer",
    category: "contact",
    note: "Footer with a sunset behind a lit pixel city.",
    Component: contact.SkylineFooter,
  },
]
